document.addEventListener('DOMContentLoaded', () => {
    const translations = {
        en: {
            // --- UI chrome ---
            ui_status_line: "STATUS: ONLINE · OPEN TO WORK",
            nav_overview: "Overview",
            nav_logs: "Project_Logs",
            nav_academy: "Academy_Data",
            nav_contact: "Contact",
            vitals_title: "System_Vitals",
            vital_backend: "BACKEND (Go/Node/Py)",
            vital_frontend: "FRONTEND (React/JS)",
            vital_ai: "AI & AUTOMATION",
            vital_data: "DATA (SQL/Mongo)",
            lang_toggle: "LANG: EN",
            inspector_title: "Sys_Inspector",
            stat_projects: "Projects_Logged",
            stat_certs: "Certs_Unlocked",
            stat_languages: "Languages",
            logs_title: "Realtime_Logs",
            cmd_placeholder: "Type 'help' or use the menu...",
            // --- View titles / subtitles ---
            title_overview: "> INIT_SEQUENCE_COMPLETE",
            subtitle_overview: "Welcome to JDB-OS Core. Profile loaded.",
            title_experience: "> PROJECT_LOGS.EXE",
            subtitle_experience: "Executing timeline data retrieval...",
            title_education: "> ACADEMY_DATA.BIN",
            subtitle_education: "Decrypting academic records...",
            title_contact: "> COMM_LINK.SH",
            subtitle_contact: "Establishing secure communication protocols...",
            // --- Profile / hero ---
            name: "Juan David Benavides",
            hero_title: "Full Stack Developer & AI Data Engineer",
            hero_subtitle: "Software Developer and AI Data Analyst specializing in AI-First solutions. I design and deploy AI agents, build high-scale architectures with Go (Golang), and develop full-stack applications with the MERN stack — delivering scalable, data-driven products in Agile environments.",
            hero_location: "Bogotá, Colombia",
            // --- Skills ---
            skills_title: "Skills & Technologies",
            ai_skills_title: "AI & Automation",
            frontend_skills_title: "Frontend",
            backend_skills_title: "Backend",
            db_skills_title: "Databases & Tools",
            // --- Experience (Project_Logs) ---
            experience_title: "Professional Experience",
            responsibilities_title: "Responsibilities",
            achievements_title: "Key Achievements",
            tech_title: "Technologies",
            current_badge: "Current",
            view_github: "View on GitHub",
            job_1_title: "Growth, Automation & Data Architecture Platform",
            job_1_company: "Bia",
            job_1_period: "Nov 2025 – Present · Hybrid",
            job_1_description: "Technical leadership in software and analytics solutions focused on business growth, process automation, and corporate data governance.",
            job_1_resp_1: "Designed the platform architecture using Go (Golang) for the backend and React for the frontend, ensuring high availability and performance.",
            job_1_resp_2: "Led the design and construction of a corporate Data Warehouse with a layered structure to centralize company-wide databases.",
            job_1_resp_3: "Integrated real-time data streams and utilized Claude Code to optimize business logic and accelerate the SDLC.",
            job_1_resp_4: "Developed advanced analytics modules transforming raw data into strategic daily performance insights.",
            job_1_ach_1: "Built an automated business analysis system that significantly reduced data interpretation time for the Growth team.",
            job_1_ach_2: "Created an interactive dashboard to detect anomalies and daily performance variations, enabling data-driven decision-making.",
            job_2_title: "Cinema Management Platform",
            job_2_company: "Campuslands",
            job_2_period: "Nov 2024 – Aug 2025 · Bogotá",
            job_2_description: "Full-stack web application to manage cinema operations — movies, users, and showtimes.",
            job_2_resp_1: "Responsible for the full-stack development of the web application.",
            job_2_resp_2: "Designed and implemented the backend with Node.js and Express, including a RESTful API for CRUD operations.",
            job_2_resp_3: "Integrated JWT for user authentication and endpoint protection.",
            job_2_resp_4: "Managed the database schema and data models in MongoDB.",
            job_2_ach_1: "Launched a fully functional platform capable of managing all core cinema operations.",
            job_2_ach_2: "Delivered a secure and scalable backend ensuring data integrity and controlled access.",
            job_3_title: "Bakery E-commerce Platform",
            job_3_company: "Coderhouse",
            job_3_period: "Jan 2024 – Jan 2025 · Virtual",
            job_3_description: "E-commerce application for a bakery with a focus on frontend development.",
            job_3_resp_1: "Designed and built an interactive, responsive UI to display a product catalog.",
            job_3_resp_2: "Implemented React Router for seamless SPA client-side navigation.",
            job_3_resp_3: "Built global cart state management (add, remove, summarize) using the React Context API.",
            job_3_ach_1: "Developed a complete and functional shopping cart, improving the purchasing experience.",
            job_3_ach_2: "Created a modular and maintainable codebase using React's component-based architecture.",
            // --- Education (Academy_Data) ---
            education_title: "Education & Training",
            degree_1: "Technical Degree in Software Programming",
            degree_1_place: "Campuslands · Bogotá, Colombia",
            degree_1_period: "Nov 2024 – Aug 2025",
            degree_2: "Web and Backend Development",
            degree_2_place: "Coderhouse · Virtual",
            degree_2_period: "Jan 2024 – Jan 2025",
            diplomas_title: "Certificates",
            diplomas_text: "Certified across the full web development stack — from frontend to backend.",
            // --- Contact (Comm_Link) ---
            contact_links_title: "Network Link Terminal",
            contact_form_title: "Transmission Port",
            contact_github: "GITHUB_REPO",
            contact_linkedin: "LINKEDIN_PROFILE",
            contact_email: "SECURE_EMAIL",
            form_name_placeholder: "SENDER_ID",
            form_msg_placeholder: "PAYLOAD_DATA...",
            form_submit: "Send Transmission",
            form_sent: "TRANSMISSION SENT — I'll reply soon.",
            // --- Footer copy (kept for parity) ---
            footer_copy: `© ${new Date().getFullYear()} Juan David Benavides. All Rights Reserved.`
        },
        es: {
            ui_status_line: "ESTADO: EN LÍNEA · DISPONIBLE",
            nav_overview: "General",
            nav_logs: "Registro_Proyectos",
            nav_academy: "Datos_Academia",
            nav_contact: "Contacto",
            vitals_title: "Constantes_Sistema",
            vital_backend: "BACKEND (Go/Node/Py)",
            vital_frontend: "FRONTEND (React/JS)",
            vital_ai: "IA & AUTOMATIZACIÓN",
            vital_data: "DATOS (SQL/Mongo)",
            lang_toggle: "IDIOMA: ES",
            inspector_title: "Inspector_Sis",
            stat_projects: "Proyectos",
            stat_certs: "Certificados",
            stat_languages: "Idiomas",
            logs_title: "Logs_En_Vivo",
            cmd_placeholder: "Escribe 'help' o usa el menú...",
            title_overview: "> SECUENCIA_INICIO_COMPLETA",
            subtitle_overview: "Bienvenido al núcleo JDB-OS. Perfil cargado.",
            title_experience: "> REGISTRO_PROYECTOS.EXE",
            subtitle_experience: "Recuperando datos de la línea de tiempo...",
            title_education: "> DATOS_ACADEMIA.BIN",
            subtitle_education: "Descifrando registros académicos...",
            title_contact: "> ENLACE_COM.SH",
            subtitle_contact: "Estableciendo protocolos de comunicación segura...",
            name: "Juan David Benavides",
            hero_title: "Desarrollador Full Stack & AI Data Engineer",
            hero_subtitle: "Desarrollador de Software y AI Data Analyst especializado en soluciones IA-First. Diseño y despliego agentes de IA, construyo arquitecturas de alta escala con Go (Golang), y desarrollo aplicaciones full-stack con el stack MERN — entregando productos escalables y basados en datos en entornos ágiles.",
            hero_location: "Bogotá, Colombia",
            skills_title: "Habilidades y Tecnologías",
            ai_skills_title: "IA & Automatización",
            frontend_skills_title: "Frontend",
            backend_skills_title: "Backend",
            db_skills_title: "Bases de Datos & Herramientas",
            experience_title: "Experiencia Profesional",
            responsibilities_title: "Roles y Responsabilidades",
            achievements_title: "Logros Clave",
            tech_title: "Tecnologías",
            current_badge: "Actual",
            view_github: "Ver en GitHub",
            job_1_title: "Plataforma de Growth, Automatización y Arquitectura de Datos",
            job_1_company: "Bia",
            job_1_period: "Nov 2025 – Presente · Híbrido",
            job_1_description: "Liderazgo técnico en el desarrollo de soluciones de software y analítica, centradas en el crecimiento del negocio, la automatización de procesos y la gobernanza de datos corporativos.",
            job_1_resp_1: "Diseñé la arquitectura de la plataforma usando Go (Golang) para el backend y React para el frontend, garantizando alta disponibilidad y rendimiento.",
            job_1_resp_2: "Lideré el diseño y construcción de un Data Warehouse corporativo con estructura por capas para centralizar las bases de datos de la compañía.",
            job_1_resp_3: "Integré flujos de datos en tiempo real y utilicé Claude Code para optimizar la lógica de negocio y acelerar el ciclo de vida de desarrollo.",
            job_1_resp_4: "Desarrollé módulos de analítica avanzada para transformar datos crudos en insights estratégicos de rendimiento diario.",
            job_1_ach_1: "Desarrollé un sistema de análisis automático que redujo significativamente el tiempo de interpretación de datos para el equipo de Growth.",
            job_1_ach_2: "Creé un panel de control interactivo para detectar anomalías y variaciones de rendimiento diario, facilitando la toma de decisiones basada en datos.",
            job_2_title: "Plataforma de Gestión de Cines",
            job_2_company: "Campuslands",
            job_2_period: "Nov 2024 – Ago 2025 · Bogotá",
            job_2_description: "Aplicación web full-stack para gestionar operaciones de un cine — películas, usuarios y horarios.",
            job_2_resp_1: "Responsable del desarrollo full-stack de la aplicación web.",
            job_2_resp_2: "Diseñé e implementé el backend con Node.js y Express, incluyendo una API RESTful para operaciones CRUD.",
            job_2_resp_3: "Integré JWT para la autenticación de usuarios y protección de endpoints.",
            job_2_resp_4: "Gestioné el esquema de la base de datos y modelos de datos en MongoDB.",
            job_2_ach_1: "Lancé una plataforma completamente funcional capaz de gestionar todas las operaciones principales del cine.",
            job_2_ach_2: "Entregué un backend seguro y escalable garantizando la integridad de los datos y el acceso controlado.",
            job_3_title: "Plataforma de E-commerce para Pastelería",
            job_3_company: "Coderhouse",
            job_3_period: "Ene 2024 – Ene 2025 · Virtual",
            job_3_description: "Aplicación de e-commerce para una pastelería con enfoque en el desarrollo frontend.",
            job_3_resp_1: "Diseñé y construí una interfaz de usuario interactiva y responsiva para mostrar un catálogo de productos.",
            job_3_resp_2: "Implementé React Router para la navegación del lado del cliente, creando una experiencia SPA fluida.",
            job_3_resp_3: "Construí la gestión de estado global del carrito (añadir, eliminar, resumir) usando la Context API de React.",
            job_3_ach_1: "Desarrollé un sistema de carrito de compras completo y funcional, mejorando la experiencia de compra.",
            job_3_ach_2: "Creé una base de código modular y mantenible aprovechando la arquitectura de componentes de React.",
            education_title: "Formación Académica",
            degree_1: "Técnico en Programación de Software",
            degree_1_place: "Campuslands · Bogotá, Colombia",
            degree_1_period: "Nov 2024 – Ago 2025",
            degree_2: "Desarrollo Web y Backend",
            degree_2_place: "Coderhouse · Virtual",
            degree_2_period: "Ene 2024 – Ene 2025",
            diplomas_title: "Certificados",
            diplomas_text: "Certificado en el stack completo de desarrollo web — frontend y backend.",
            contact_links_title: "Terminal de Enlace de Red",
            contact_form_title: "Puerto de Transmisión",
            contact_github: "REPO_GITHUB",
            contact_linkedin: "PERFIL_LINKEDIN",
            contact_email: "EMAIL_SEGURO",
            form_name_placeholder: "ID_REMITENTE",
            form_msg_placeholder: "DATOS_MENSAJE...",
            form_submit: "Enviar Transmisión",
            form_sent: "TRANSMISIÓN ENVIADA — responderé pronto.",
            footer_copy: `© ${new Date().getFullYear()} Juan David Benavides. Todos los derechos reservados.`
        }
    };

    // Expose for the logic added in Tasks 4–5.
    window.__JDBOS__ = { translations };
});
